"use client";

import Box from "@mui/material/Box";
import Button from "@mui/material/Button";
import Stack from "@mui/material/Stack";
import Typography from "@mui/material/Typography";
import AutoAwesomeIcon from "@mui/icons-material/AutoAwesome";
import ShuffleIcon from "@mui/icons-material/Shuffle";
import { useCallback } from "react";

export default function InsightsPanel({ insights, onShuffle }) {
  const handleShuffle = useCallback(() => {
    if (onShuffle) onShuffle();
  }, [onShuffle]);

  return (
    <Stack
      spacing={2}
      sx={{
        borderRadius: 3,
        p: 3,
        background:
          "linear-gradient(180deg, rgba(201,160,63,0.12) 0%, rgba(11,11,11,0.95) 100%)",
        border: "1px solid rgba(201,160,63,0.2)",
        height: "100%",
      }}
    >
      <Stack direction="row" alignItems="center" spacing={1}>
        <AutoAwesomeIcon sx={{ color: "primary.light" }} />
        <Typography variant="h6" sx={{ fontWeight: 600 }}>
          AI Insights
        </Typography>
      </Stack>
      <Typography variant="body2" color="text.secondary">
        Generated by sending KPI deltas and traffic cohorts to OpenAI for summarization. Use this to
        open stakeholder slides or annotate release notes.
      </Typography>
      <Stack spacing={2} sx={{ flexGrow: 1, justifyContent: "space-between" }}>
        <Stack spacing={2} mt={1.5}>
          {insights.map((insight, index) => (
            <Box
              key={`${insight}-${index}`}
              sx={{
                p: 2,
                borderRadius: 2,
                backgroundColor: "rgba(201,160,63,0.06)",
                border: "1px solid rgba(201,160,63,0.18)",
              }}
            >
              <Typography variant="body2" sx={{ lineHeight: 1.6 }}>
                {insight}
              </Typography>
            </Box>
          ))}
        </Stack>
        <Button
          variant="outlined"
          startIcon={<ShuffleIcon />}
          onClick={handleShuffle}
          sx={{
            alignSelf: "flex-start",
            borderColor: "rgba(201,160,63,0.35)",
            color: "primary.light",
          }}
        >
          Generate new insight
        </Button>
      </Stack>
    </Stack>
  );
}

